### PR TITLE
Consistency in the type used for the number of time bins (RT3102)

### PR DESCRIPTION
**Pull request by plexoos**
Cleaned up conditional statements by removing constant arguments
No change in logic is expected

### CODE REVIEW

**Comment by MustafaMustafa** [comment]
Is there any reason not to use the standard std::numeric_limits<unsigned char>::max() instead?

**Comment by plexoos** [comment]
Should be the same I guess. Why?

**Comment by MustafaMustafa** [comment]
This is a C++ code and we should try to avoid C macros whenever possible. I am sure you know all the arguments for why we should abandon macros.

**Comment by plexoos** [comment]
ah... yes, std::numeric_limits is more C++ish
Something tells me those climit macroses are really small. I wouldn't be surprised if inside those std::numeric_limits they reference the same macroses

**Comment by MustafaMustafa** [comment]
I doubt they do that. 

I would also use std::numeric_limits<unsigned char>::quiet_NaN() as a default value instead of max(), but this could be a little unconventional for our coders.

**Comment by plexoos** [comment]
I call it the same :)

<pre>
#define __SCHAR_MAX__ 127
template<>  struct numeric_limits<unsigned char> {
...
static unsigned char max() throw()   { return __SCHAR_MAX__ * 2U + 1; }
...
}
</pre>

vs 

<pre>
#  define UCHAR_MAX  255
</pre>

And for the quiet_NaN():
<pre>
static unsigned char quiet_NaN() throw()  { return static_cast<unsigned char>(0); }
</pre>
so it is just a zero

**Comment by MustafaMustafa** [comment]
Thank you for the extra information @plexoos, I did not know that.

**Pull request merged**
